from django.urls import path
from CHOCOLICA_APP import views
urlpatterns = [
    path('indexpage/',views.indexpage,name='indexpage'),
    path('addadminpage/',views.addadminpage,name='addadminpage'),
    path('saveadmindata/', views.saveadmindata, name='saveadmindata'),
    path('displayadminpage/', views.displayadminpage, name='displayadminpage'),
    path('editadmindata/<int:dataid>/', views.editadmindata, name='editadmindata'),
    path('updateadmindata/<int:dataid>/', views.updateadmindata, name='updateadmindata'),
    path('deleteadmindata/<int:dataid>/', views.deleteadmindata, name='deleteadmindata'),
    path('addcategorypage/',views.addcategorypage,name='addcategorypage'),
    path('savecategorydata/', views.savecategorydata, name='savecategorydata'),
    path('displaycategorypage/', views.displaycategorypage, name='displaycategorypage'),
    path('displaycategorypage/',views.displaycategorypage,name='displaycategorypage'),
    path('editcategorydata/<int:dataid>/', views.editcategorydata, name='editcategorydata'),
    path('updatecategorydata/<int:dataid>/', views.updatecategorydata, name='updatecategorydata'),
    path('deletecategorydata/<int:dataid>/', views.deletecategorydata, name='deletecategorydata'),
    path('addproductpage/',views.addproductpage,name='addproductpage'),
    path('saveproductdata/', views.saveproductdata, name='saveproductdata'),
    path('displayproductpage/', views.displayproductpage, name='displayproductpage'),
    path('displayproductpage/',views.displayproductpage,name='displayproductpage'),
    path('editproductdata/<int:dataid>/', views.editproductdata, name='editproductdata'),
    path('updateproductdata/<int:dataid>/', views.updateproductdata, name='updateproductdata'),
    path('deleteproductdata/<int:dataid>/', views.deleteproductdata, name='deleteproductdata'),
    path('loginpage/', views.loginpage, name='loginpage'),
    path('savelogindata/', views.savelogindata, name='savelogindata'),
    path('logoutpage/', views.logoutpage, name='logoutpage'),
    path('displaymessage/', views.displaymessage, name='displaymessage'),
]