# Generated by Django 4.1.3 on 2022-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHOCOLICA_APP', '0002_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
