# Generated by Django 4.1.3 on 2023-01-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHOCOLICA_APP', '0003_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
